version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assembleia
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  assembleia:
    container_name: assembleia
    image: assembleia:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - postgres
    links:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - assembleia
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - assembleia
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  postgres:
    driver: local

networks:
  assembleia:
    name: assembleia